# We'll try to write the alg for Hill Cipher

Defining Basic Given Stuff

In [16]:
import numpy as np
hill_cipher = []
chosen_matrix = np.array([[1, 2],
                          [0, 3]])

given_text = input("Enter the Text to Encode").lower().replace(' ', '')

# Add Dummy character if odd
if len(given_text) % 2 == 1:
    given_text = given_text + '#'

print("Here is your input:", given_text)

# convert to column matrix with alphanumeric equivalent
paired_up = [np.array([[ord(given_text[i]) - 96, ord(given_text[i+1]) - 96]]).T for i in range(0, len(given_text), 2)]

for i in range(len(paired_up)):
    multiplied_pair_result = np.matmul(chosen_matrix, paired_up[i])
    
    # Convert back to character and append to final answer
    hill_cipher.append([chr((int(i)) % 26 + 96) for i in multiplied_pair_result])
    
# Flatten the array
hill_cipher = [val for sublist in hill_cipher for val in sublist]
print("The Hill Cipher for your Input is: ", ''.join(hill_cipher))

Here is your input: donottouch
The Hill Cipher for your Input is:  hsrshheksx


In [2]:
for i in hill_cipher:
    for j in i:
        print(j)

i
l
r
e


In [3]:
a = np.array([[4, 15]]).T
print(a)

[[ 4]
 [15]]


In [4]:
multiplied = np.matmul(chosen_matrix, a)

In [5]:
hill_cipher = [chr((int(i)) % 26 + 96) for i in multiplied]

In [6]:
ord('a')-96

1

In [7]:
hill_cipher

['h', 's']

## Now trying the deciphering Alg

In [100]:
cipher_text = 'hsrshheksx'.lower()
chosen_matrix = np.array([[1, 2],
                          [0, 3]])
print(chosen_matrix)
inverse_matrix = np.linalg.inv(chosen_matrix)
print("The inverse is")
print(inverse_matrix) # but this is not modded with 26

for i in inverse_matrix:
    for j in i:
        print(round(j%26))

print(round(np.linalg.det(chosen_matrix))%26)
        


[[1 2]
 [0 3]]
The inverse is
[[ 1.         -0.66666667]
 [ 0.          0.33333333]]
1
25
0
0
3


In [101]:
adjoint_matrix = np.dot(inverse_matrix, round(np.linalg.det(chosen_matrix)))
print(adjoint_matrix)
print(inverse_matrix[0][1]%26)
print(np.divide(adjoint_matrix, np.linalg.det(chosen_matrix)))

[[ 3. -2.]
 [ 0.  1.]]
25.333333333333332
[[ 1.         -0.66666667]
 [ 0.          0.33333333]]


In [102]:
paired_up = [np.array([[ord(cipher_text[i]) - 96, ord(cipher_text[i+1]) - 96]]).T for i in range(0, len(cipher_text), 2)]

In [103]:
paired_up

[array([[ 8],
        [19]]),
 array([[18],
        [19]]),
 array([[8],
        [8]]),
 array([[ 5],
        [11]]),
 array([[19],
        [24]])]

In [39]:
np.matmul(inverse_matrix, paired_up[0])

array([[-4.66666667],
       [ 6.33333333]])

In [145]:
hill_cipher = []
chosen_matrix = np.array([[1, 2],
                          [0, 3]])

given_text = input("Enter the Text to Encode").lower().replace(' ', '')

# Add Dummy character if odd
if len(given_text) % 2 == 1:
    given_text = given_text + '#'

print("Here is your input:", given_text)

# convert to column matrix with alphanumeric equivalent
paired_up = [np.array([[ord(given_text[i]) - 96, ord(given_text[i+1]) - 96]]).T for i in range(0, len(given_text), 2)]
paired_up

Here is your input: 


[]

In [61]:
4 % 2

0

In [69]:
-5 % 2

1

In [71]:
5.2 % 2

1.2000000000000002

In [74]:
2%26

2

In [75]:
-2/26

-0.07692307692307693

In [106]:
np.linalg.det(chosen_matrix)

3.0000000000000004

In [104]:
some_shit = np.dot(adjoint_matrix, 9)

In [105]:
for i in some_shit:
    for j in i:
        print(round(j%26))

1
8
0
9


In [89]:
%26

1

## Alright after all that lets start again

In [150]:
cipher_text = 'GTNKGKDUSK'.lower()
chosen_matrix = np.array([[5, 6],
                          [2, 3]])
print(chosen_matrix)

[[5 6]
 [2 3]]


## First we find the adjoint of the matrix, and then the determinant of the chosen matrix

In [151]:
print("the adjoint of the matrix is")
determinant = round(np.linalg.det(chosen_matrix))
inverse_matrix = np.linalg.inv(chosen_matrix)
adjoint_matrix = np.dot(inverse_matrix, determinant)
adjoint_matrix

the adjoint of the matrix is


array([[ 3., -6.],
       [-2.,  5.]])

## then we find the multiplicative inverse of the determinant module n

Extended Eucleadean Algorithm is used to find the number x which when multiplied with the determinant, and then the result modded with n, will give you 1

This inverse mod n is only possible when the GCD(n, determinant) is 1, which is like guaranteed if n is prime, obviously.

In [152]:
# function for extended Euclidean Algorithm 
def gcdExtended(a, b): 
    # Base Case 
    if a == 0 :  
        return b,0,1
             
    gcd,x1,y1 = gcdExtended(b%a, a) 

    # Update x and y using results of recursive call
    x = y1 - (b//a) * x1 
    y = x1 
    return gcd,x,y

In [153]:
gcd, x, mul_inverse = gcdExtended(26, determinant)
print('the multiplicative inverse mod 26 of the determinant is', mul_inverse)

the multiplicative inverse mod 26 of the determinant is 9


## then we multiply that number x with the entire adjoint matrix

In [154]:
inverse_mod_matrix = np.dot(adjoint_matrix, mul_inverse)
inverse_mod_matrix

array([[ 27., -54.],
       [-18.,  45.]])

## then we find mod n of the resulting matrix

In [155]:
for i in range(2):
    for j in range(2):
        inverse_mod_matrix[i][j] = inverse_mod_matrix[i][j] % 26
inverse_mod_matrix

array([[ 1., 24.],
       [ 8., 19.]])

## Now we pair the cipher text, and then convert them to column matrixes

In [161]:
paired_up = [np.array([[ord(cipher_text[i]) - 96, ord(cipher_text[i+1]) - 96]]).T \
                for i in range(0, len(cipher_text), 2)]

[array([[ 7],
        [20]]),
 array([[14],
        [11]]),
 array([[ 7],
        [11]]),
 array([[ 4],
        [21]]),
 array([[19],
        [11]])]

In [218]:
hill_decipher = []
import math
for i in paired_up:
    multiplied_matrix = np.matmul(inverse_mod_matrix, i)
    for i in range(2):
        multiplied_matrix[i] = multiplied_matrix[i] % 26
    for i in multiplied_matrix:
        hill_decipher.append(chr(round(i[0]) + 96))
print("The Decrypted Text is: ", ''.join(hill_decipher))

The Decrypted Text is:  strikenoww


In [224]:
cipher_text = 'GTNKGKDUSK'.lower()
chosen_matrix = np.array([[5, 6],
                          [2, 3]])
print("Your input is: ", cipher_text)
print("chosen Matrix is: ")
print(chosen_matrix)

# function for extended Euclidean Algorithm 
# Extended Eucleadean Algorithm is used to find the number x 
# which when multiplied with the determinant, and then the result
# modded with n, will give you 1

def gcdExtended(a, b): 
    # Base Case 
    if a == 0 :  
        return b,0,1
             
    gcd,x1,y1 = gcdExtended(b%a, a) 

    # Update x and y using results of recursive call
    x = y1 - (b//a) * x1 
    y = x1 
    return gcd,x,y



# First we find the adjoint of the matrix, and then the determinant of the chosen matrix

determinant = round(np.linalg.det(chosen_matrix))
inverse_matrix = np.linalg.inv(chosen_matrix)
adjoint_matrix = np.dot(inverse_matrix, determinant)

# then we find the multiplicative inverse of the determinant module n

gcd, x, mul_inverse = gcdExtended(26, determinant)

# then we multiply that number x with the entire adjoint matrix

inverse_mod_matrix = np.dot(adjoint_matrix, mul_inverse)

# then we find mod 26 of the resulting matrix

for i in range(2):
    for j in range(2):
        inverse_mod_matrix[i][j] = inverse_mod_matrix[i][j] % 26

## Now we pair the cipher text, and then convert them to column matrixes

paired_up = [np.array([[ord(cipher_text[i]) - 96, ord(cipher_text[i+1]) - 96]]).T \
                for i in range(0, len(cipher_text), 2)]

# Finally simply decipher them back to their alphanumeric values

hill_decipher = []
import math
for i in paired_up:
    multiplied_matrix = np.matmul(inverse_mod_matrix, i)
    for i in range(2):
        multiplied_matrix[i] = multiplied_matrix[i] % 26
    for i in multiplied_matrix:
        hill_decipher.append(chr(round(i[0]) + 96))
print("The Decrypted Text is: ", ''.join(hill_decipher))


Your input is:  gtnkgkdusk
chosen Matrix is: 
[[5 6]
 [2 3]]
The Decrypted Text is:  strikenoww
