# Assignment 8 - Numpy Stufff

In [4]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr = np.array((1, 2, 3, 4, 5))
arr

array([1, 2, 3, 4, 5])

In [10]:
np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]], ndmin=2)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
arr.ndim

1

In [21]:
s_box = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

s_box = np.array(s_box)
s_box

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
s_box.ndim

2

In [23]:
s_box

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr = np.array([[(1, 2, 3), (4, 5, 6)],[(7, 8, 9), (10, 11, 12)]])

In [32]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr[0][0]


array([1, 2, 3])

In [47]:
arr[0][0][0].dtype

dtype('int64')

In [50]:
np.array(["abcd", "sadoifj"])

array(['abcd', 'sadoifj'], dtype='<U7')

In [65]:
array = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 4], range(5), range(5)])
array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [66]:
array.shape

(4, 5)

In [67]:
array.reshape(5, 4)

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 4, 0, 1],
       [2, 3, 4, 0],
       [1, 2, 3, 4]])

In [68]:
array.transpose()

array([[1, 1, 0, 0],
       [2, 2, 1, 1],
       [3, 3, 2, 2],
       [4, 4, 3, 3],
       [5, 4, 4, 4]])

In [69]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
array = np.zeros(array.shape)
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.array(range(0, 10, 2))

array([0, 2, 4, 6, 8])

In [81]:
type(array)

numpy.ndarray

In [82]:
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [83]:
print(array[1])

[0. 0. 0. 0. 0.]


In [86]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [88]:
x = np.arange(10)
y = np.arange(10)

In [92]:
np.sum([x, y], axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])